name: Docker_Login

on: [ push ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps: 
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: cluster-1
          location: us-central1-c
          credentials: ${{ secrets.GCP_SA_KEY }}       
