name: Docker_Login

on: [ push ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:    
      - name: GCP Github Action
        uses: google-github-actions/setup-gcloud@master
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            
      - name: Use gcloud CLI
        run: gcloud info           
