
name: WAR_To_Docker

on: [push]

jobs:
  WAR_To_Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: WAR_With_Gradle
          path: ./build/libs/*.war
          

      - uses: actions/download-artifact@v2
        with:
          name: WAR_With_Gradle

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ywd-devops:latest
      
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: cluster-1
          location: us-central1-c
          credentials: ${{ secrets.GCP_SA_KEY }}
          
      - name: get-all
        run: kubectl get all
