name: TEST-Checkout


on:
  push:
    branches: [ main ]
  
jobs:
  Setup_GCP:
    runs-on: ubuntu-latest
    
    steps:
#      - name: Checkout
#        uses: actions/checkout@v2


      - name: GCP Github Action
        uses: google-github-actions/setup-gcloud@master
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            
      - name: Use gcloud CLI
		    run: gcloud info
